### ISSUE TITLE
Dates possibly not being loaded from data

### ISSUE THREAD

**Issue by samchrisinger** [samchrisinger/ember-osf#1]
> I noticed that the date created and modified are both wrong. After investigating the issue, I found that they are sent in the json, but end up blank. Looking at this ember-moment code inside helper-compute.js, I discovered this:
```
if (isBlank(datetime)) {
  if (allowEmpty) {
    return;
  } else {
    Ember.Logger.warn('ember-moment: an empty value (null, undefined, or "") was passed to moment-format');
  }
}
```
The warning is logged which implies that it is coming back as blank.Title and category work fine and even setting the attr type of dateCreated and dateModified to string didn't do anything either. It still came in empty.

**Comment by Macainian** [comment]
What I see is that it is being parsed correctly, but it is destroyed after calling the super for normalizeArrayResponse. Here is how I tested:

normalizeArrayResponse(_, __, payload) {
    payload.data = payload.data.map((record) => {
        record.attributes = this._normalizeAttributes(record.attributes);
        return record;
    });
    console.log("Payload data: " + JSON.stringify(payload.data));
    var a = this._super(...arguments);
    console.log(a);
    return a;
}

The first console log has the datetime, but the second one does not. In fact the second one doesn't even have the attributes for date_created and date_modified at all.

**Comment by samchrisinger** [comment]
@Macainian thanks much for finding this! Looks like all of the underscore_seperated attributes coming from the OSF API would have gotten ignored because they were not being accessed correctly.
